import { forwardRef, useEffect, useImperativeHandle, useRef, type ReactNode } from 'react'
import { STUDY_REPORT_SECONDS, reportStudySeconds } from './studyLog'

// Types minimaux de la YouTube IFrame Player API.
interface YTPlayer {
  getCurrentTime(): number
  seekTo(seconds: number, allowSeekAhead: boolean): void
  playVideo(): void
  pauseVideo(): void
  getPlayerState(): number
  setPlaybackRate(rate: number): void
  destroy(): void
  // Undocumented part of the API, the only way to choose a caption track after loading (YC-59):
  // every call is guarded, the menu falls back to on / off if YouTube removes it.
  loadModule?(name: string): void
  unloadModule?(name: string): void
  getOption?(module: string, option: string): unknown
  setOption?(module: string, option: string, value: unknown): void
}

/** A caption track YouTube offers for the video; `auto` when generated by YouTube. */
export interface CaptionTrack {
  languageCode: string
  label: string
  auto: boolean
}

/** What the page can ask of the player (YC-6, YC-59). */
export interface FocusPlayerHandle {
  /** Jumps to `seconds` and plays from there. */
  seekTo(seconds: number): void
  /** Moves by `delta` seconds from where it is (J / L). */
  seekBy(delta: number): void
  /** Pauses when playing, plays otherwise (space). */
  togglePlay(): void
  setRate(rate: number): void
  /** Shows the captions of `languageCode` ('' for the first one offered), or hides them (null). */
  setCaptions(languageCode: string | null): void
  /** Plays again from the start (« Revoir » of the end card, YC-60). */
  restart(): void
}

/** The tracks YouTube gives once its captions module is loaded; null when it gives none. */
function readTracks(player: YTPlayer): CaptionTrack[] | null {
  try {
    const list = player.getOption?.('captions', 'tracklist')
    if (!Array.isArray(list) || !list.length) return null
    return list.map((t: { languageCode?: string; languageName?: string; displayName?: string; kind?: string }) => ({
      languageCode: String(t.languageCode ?? ''),
      label: String(t.languageName ?? t.displayName ?? t.languageCode ?? ''),
      auto: t.kind === 'asr',
    }))
  } catch {
    return null
  }
}
interface YTNamespace {
  Player: new (el: HTMLElement, opts: unknown) => YTPlayer
  PlayerState: { PLAYING: number; PAUSED: number; ENDED: number }
}
declare global {
  interface Window {
    YT?: YTNamespace
    onYouTubeIframeAPIReady?: () => void
  }
}

let apiPromise: Promise<void> | null = null
function loadYouTubeApi(): Promise<void> {
  if (window.YT?.Player) return Promise.resolve()
  if (apiPromise) return apiPromise
  apiPromise = new Promise((resolve) => {
    const previous = window.onYouTubeIframeAPIReady
    window.onYouTubeIframeAPIReady = () => {
      previous?.()
      resolve()
    }
    const tag = document.createElement('script')
    tag.src = 'https://www.youtube.com/iframe_api'
    document.head.appendChild(tag)
  })
  return apiPromise
}

interface FocusPlayerProps {
  youtubeId: string
  title: string
  /** Position de reprise (secondes). */
  startSeconds?: number
  /** Appelé périodiquement et aux pauses/fin avec la position courante. */
  onProgress?: (seconds: number) => void
  /** Appelé quand la vidéo se termine. */
  onEnded?: () => void
  /** Current position, every second while playing and right after a seek (YC-6). */
  onTimeUpdate?: (seconds: number) => void
  /** Reading speed to start with, and its changes (YC-59). */
  rate?: number
  onRateChange?: (rate: number) => void
  /** Caption language to show from the start (kept from one video to the next), null for none. */
  captions?: string | null
  /** The caption tracks once YouTube gives them (YC-59). */
  onCaptionTracks?: (tracks: CaptionTrack[] | null, shown: string | null) => void
  /** Called each time the video starts playing (YC-60: the end card goes away). */
  onPlay?: () => void
  /** Plays as soon as it is ready: the user asked for this video (« Lire la suivante », YC-60). */
  autoplay?: boolean
  /** Shown in place of the video, at its size or taller (the end card, YC-60). */
  overlay?: ReactNode
  /** Right under the video, inside the stage: the bar cut at the chapters (YC-88). */
  below?: ReactNode
}

/** The language of the captions shown, null when none or unknown. */
function readShown(player: YTPlayer): string | null {
  try {
    const track = player.getOption?.('captions', 'track') as { languageCode?: string } | undefined
    return track?.languageCode || null
  } catch {
    return null
  }
}

/** How long a seek by J / L counts as « just made » for the next one. */
const SEEK_CHAIN_MS = 1000

/** Shows the captions of `languageCode`, or hides them (null), through the undocumented module. */
function applyCaptions(player: YTPlayer, languageCode: string | null) {
  try {
    if (languageCode === null) player.unloadModule?.('captions')
    else {
      player.loadModule?.('captions')
      // '' means « whatever YouTube offers first » (the tracks are not known yet).
      if (languageCode) player.setOption?.('captions', 'track', { languageCode })
    }
  } catch {
    // The undocumented part refused: the menu keeps showing what was asked, nothing breaks.
  }
}

/**
 * Lecteur focus via la YouTube IFrame Player API (SDK JS).
 * Reprend à `startSeconds`, remonte la position via `onProgress`, signale la fin via `onEnded`.
 * Sans distraction : rel=0, modestbranding, iv_load_policy=3.
 */
export const FocusPlayer = forwardRef<FocusPlayerHandle, FocusPlayerProps>(function FocusPlayer(
  {
    youtubeId,
    title,
    startSeconds = 0,
    onProgress,
    onEnded,
    onTimeUpdate,
    rate = 1,
    onRateChange,
    captions = null,
    onCaptionTracks,
    onPlay,
    autoplay = false,
    overlay,
    below,
  },
  ref,
) {
  const containerRef = useRef<HTMLDivElement>(null)
  const playerRef = useRef<YTPlayer | null>(null)
  const onProgressRef = useRef(onProgress)
  const onEndedRef = useRef(onEnded)
  const onTimeUpdateRef = useRef(onTimeUpdate)
  onProgressRef.current = onProgress
  onEndedRef.current = onEnded
  onTimeUpdateRef.current = onTimeUpdate
  const rateRef = useRef(rate)
  rateRef.current = rate
  const onRateChangeRef = useRef(onRateChange)
  onRateChangeRef.current = onRateChange
  const lastSeekRef = useRef<{ to: number; at: number } | null>(null)
  const captionsRef = useRef(captions)
  captionsRef.current = captions
  const onCaptionTracksRef = useRef(onCaptionTracks)
  onCaptionTracksRef.current = onCaptionTracks
  const onPlayRef = useRef(onPlay)
  onPlayRef.current = onPlay
  const autoplayRef = useRef(autoplay)
  autoplayRef.current = autoplay

  useImperativeHandle(
    ref,
    () => ({
      seekTo(seconds: number) {
        const player = playerRef.current
        if (!player) return
        player.seekTo(seconds, true)
        player.playVideo()
        onTimeUpdateRef.current?.(seconds)
      },
      seekBy(delta: number) {
        const player = playerRef.current
        if (!player) return
        // Right after a seek YouTube still gives the old position (two quick J went back 10 s, not
        // 20, in the proof): a press soon after the last one starts from where that one went.
        const last = lastSeekRef.current
        const from = last && Date.now() - last.at < SEEK_CHAIN_MS ? last.to : player.getCurrentTime()
        const to = Math.max(0, from + delta)
        lastSeekRef.current = { to, at: Date.now() }
        player.seekTo(to, true)
        onTimeUpdateRef.current?.(to)
      },
      togglePlay() {
        const player = playerRef.current
        if (!player || !window.YT) return
        if (player.getPlayerState() === window.YT.PlayerState.PLAYING) player.pauseVideo()
        else player.playVideo()
      },
      setRate(next: number) {
        playerRef.current?.setPlaybackRate(next)
      },
      setCaptions(languageCode: string | null) {
        if (playerRef.current) applyCaptions(playerRef.current, languageCode)
      },
      restart() {
        const player = playerRef.current
        if (!player) return
        player.seekTo(0, true)
        player.playVideo()
        onTimeUpdateRef.current?.(0)
      },
    }),
    [],
  )

  useEffect(() => {
    let cancelled = false
    let player: YTPlayer | null = null
    let interval: ReturnType<typeof setInterval> | undefined

    let ticks = 0
    // Seconds really played since the last report (YC-79): counted by the clock while it plays, so a
    // seek adds nothing and a video at 2× counts the time spent, not the minutes of video.
    let played = 0
    const reportPlayed = () => {
      if (played > 0) reportStudySeconds(played)
      played = 0
    }

    const report = () => {
      const t = Math.floor(player?.getCurrentTime() ?? 0)
      if (t > 0) onProgressRef.current?.(t)
    }
    // Every second: the current position for the chapters; every fifth: the saved progress.
    const tick = () => {
      onTimeUpdateRef.current?.(player?.getCurrentTime() ?? 0)
      ticks += 1
      if (ticks % 5 === 0) report()
      played += 1
      if (played >= STUDY_REPORT_SECONDS) reportPlayed()
    }

    loadYouTubeApi().then(() => {
      if (cancelled || !containerRef.current || !window.YT) return
      const YT = window.YT
      player = new YT.Player(containerRef.current, {
        videoId: youtubeId,
        playerVars: {
          rel: 0,
          modestbranding: 1,
          iv_load_policy: 3,
          playsinline: 1,
          start: Math.floor(startSeconds),
          // Captions, when shown, in French first (YC-59); YouTube keeps them off by default.
          cc_lang_pref: 'fr',
          hl: 'fr',
        },
        events: {
          onReady: (e: { target: YTPlayer }) => {
            playerRef.current = e.target
            if (rateRef.current !== 1) e.target.setPlaybackRate(rateRef.current)
            onCaptionTracksRef.current?.(null, null)
            if (captionsRef.current !== null) applyCaptions(e.target, captionsRef.current)
            if (startSeconds > 0) e.target.seekTo(startSeconds, true)
            onTimeUpdateRef.current?.(startSeconds)
            if (autoplayRef.current) e.target.playVideo()
          },
          onPlaybackRateChange: (e: { data: number }) => onRateChangeRef.current?.(e.data),
          // The captions module tells when it is (un)loaded: the tracks can be read then.
          onApiChange: () => {
            if (player) onCaptionTracksRef.current?.(readTracks(player), readShown(player))
          },
          onStateChange: (e: { data: number }) => {
            if (e.data === YT.PlayerState.PLAYING) {
              onPlayRef.current?.()
              if (interval) clearInterval(interval)
              interval = setInterval(tick, 1000)
            } else {
              if (interval) clearInterval(interval)
              interval = undefined
              onTimeUpdateRef.current?.(player?.getCurrentTime() ?? 0)
              report()
              reportPlayed()
              if (e.data === YT.PlayerState.ENDED) onEndedRef.current?.()
            }
          },
        },
      })
    })

    return () => {
      cancelled = true
      if (interval) clearInterval(interval)
      reportPlayed()
      player?.destroy()
      playerRef.current = null
    }
  }, [youtubeId, startSeconds])

  return (
    <div>
      <div className="relative">
        {/* Under an overlay the player stays mounted, out of sight and out of the tab order. */}
        <div
          className={`aspect-video w-full overflow-hidden rounded-card bg-black ${overlay ? 'invisible absolute inset-x-0 top-0' : ''}`}
          aria-hidden={overlay ? true : undefined}
        >
          <div ref={containerRef} title={title} className="h-full w-full" />
        </div>
        {overlay}
      </div>
      {below}
      {/* Inside the stage, whose rounded corners cut what touches them (seen on the note page, YC-77). */}
      <p className="px-4 pb-3 pt-2 text-xs text-content-muted">
        Youcus retire les recommandations et l'habillage qui font dériver. Les publicités, elles,
        restent celles de YouTube : les conditions de son API interdisent de les bloquer, et elles
        rémunèrent les créateurs dont vous regardez le travail.
      </p>
    </div>
  )
})
